[package]
name = "ipc-channel"
version = "0.10.1"
description = "A multiprocess drop-in replacement for Rust channels"
authors = ["The Servo Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/ipc-channel"
edition = "2015"

[features]
force-inprocess = []
memfd = ["sc"]
unstable = []
async = ["futures"]
win32-trace = []

[dependencies]
bincode = "1"
lazy_static = "1"
libc = "0.2.12"
rand = "0.4"
serde = { version="1.0.70", features=["rc"] }
uuid = {version = "0.6", features = ["v4"]}
fnv = "1.0.3"
tempfile = "3"

[target.'cfg(any(target_os = "linux", target_os = "openbsd", target_os = "freebsd"))'.dependencies]
mio = "0.6.11"

sc = { version = "0.2.2", optional = true }
futures = { version = "0.1", optional = true }

[dev-dependencies]
crossbeam = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["errhandlingapi", "fileapi", "handleapi", "ioapiset", "memoryapi", "minwindef", "namedpipeapi", "processthreadsapi", "winerror", "winnt"] }
